apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: movies-service
  namespace: cinemaabyss
spec:
  hosts:
  - movies-service
  http:
  - route:
    - destination:
        host: movies-service
        port:
          number: 8081
