apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImJIVnVZWFJwWTJWdWMyeGhkbVZrT21kb2NGOHljazVpTUZnemNXUk1jVzFsYWpWalZrbzNkVE54VFV0TlZXdENkMll5WkZKeldYTT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
